use_frameworks!
platform :ios, '9.0'

target 'MJSwiftCore_Example' do
    
  pod 'MJSwiftCore', :path => '../'
  pod 'MJSwiftCore/Vastra', :path => '../'
  pod 'MJSwiftCore/Alamofire', :path => '../'
  pod 'MJSwiftCore/iOS', :path => '../'
  pod 'MJSwiftCore/Realm', :path => '../'
  pod 'MJSwiftCore/MJCocoaCore', :path => '../'
  pod 'MJSwiftCore/Objection', :path => '../'

  pod 'Swinject', '~> 2.4.0'
  pod 'Kingfisher', '~> 4.7.0'
  
  pod 'PromisesSwift', '~> 1.0'

  target 'MJSwiftCore_Tests' do
    inherit! :search_paths
  end
end
