use_frameworks!
platform :ios, '10.0'

target 'MJSwiftCore_Example' do
  
  pod 'MJSwiftCore', :path => '../'
  pod 'MJSwiftCore/Security', :path => '../'
  pod 'MJSwiftCore/Vastra', :path => '../'
  pod 'MJSwiftCore/Alamofire', :path => '../'
  pod 'MJSwiftCore/iOS', :path => '../'
  pod 'MJSwiftCore/Realm', :path => '../'
  pod 'MJSwiftCore/MJCocoaCore', :path => '../'
  pod 'MJSwiftCore/Objection', :path => '../'

  pod 'Swinject', '~> 2.6'
  pod 'Kingfisher', '~> 5.3'
  pod 'PromisesSwift', '~> 1.2'

  target 'MJSwiftCore_Tests' do
    inherit! :search_paths
  end
end
